import { NextRequest, NextResponse } from "next/server";

/*
 * content_negotiation_text_markdown (policy tier 2)
 *
 * A client that sends Accept: text/markdown for /pricing is an agent asking
 * for the machine-readable form. Serve the same /pricing.md file (the static
 * copy generated by machine-readable.js, which carries Content-Type
 * text/markdown) instead of the HTML page. A plain browser sends no such
 * Accept, so humans keep the HTML page. Single source of truth: the rewrite
 * targets the file, so the negotiation cannot drift from /pricing.md.
 */
export function middleware(request: NextRequest) {
  const { pathname } = new URL(request.url);
  if (pathname !== "/pricing") {
    return NextResponse.next();
  }
  const accept = request.headers.get("accept") ?? "";
  if (!accept.includes("text/markdown")) {
    return NextResponse.next();
  }
  const target = new URL("/pricing.md", request.url);
  return NextResponse.rewrite(target);
}

export const config = {
  matcher: ["/pricing"],
};